global:
  scrape_interval:     10s
  evaluation_interval: 10s

  external_labels:
    monitor: 'my-project'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 120s
    static_configs:
      - targets: ['localhost:9090']
#      - targets: ['localhost:9090','cadvisor:8080','node-exporter:9100']

  - job_name: 'java-app'
    metrics_path: 'actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['app:8765']