---
version: '3.7'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: monitoring_prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    expose:
      - 9090
    ports:
      - 9090:9090
#    links:
#      - cadvisor:cadvisor
#      - node-exporter:node-exporter
    depends_on:
      - app

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - prometheus
    container_name: monitoring_grafana
    ports:
      - 3000:3000
    links:
      - prometheus:prometheus
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboard/:/etc/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=pass
      - GF_USERS_ALLOW_SIGN_UP=false

  app:
    image: app
    container_name: java_app
    ports:
      - 8765:8765

#  node-exporter:
#    image: prom/node-exporter:latest
#    container_name: monitoring_node_exporter
#    expose:
#      - 9100
#
#  cadvisor:
#    image: google/cadvisor:latest
#    container_name: monitoring_cadvisor
#    expose:
#      - 8080